### ISSUE TITLE
`min` must be lower than `max`

### ISSUE THREAD

**Issue by leontoeides** [jprochazk/garde#38]
Thank you for this crate. I really appreciate the `validator` crate too.

I'm getting an error with this crate when a length's `min` and `max` are set to the same value.

I would like for this field to be exactly 2 characters, no more and no less.

If this is invalid, how would I express in this in `garde` without a custom rule? Or maybe this is an oversight?

Thank you for the crate and your help!

```
error: `min` must be lower than `max`
   |
34 |     #[garde(length(min = 2, max = 2))]
   |                    ^^^
```

**Comment by jprochazk** [comment]
This is definitely a bug. It should be possible to set `min` and `max` to the same value, because the comparison ops used are `<` and `>`:

https://github.com/jprochazk/garde/blob/bc4cdba4ef169424003688023f5993cfd9d20c55/garde/src/rules/length.rs#L69-L75

For the time being, you can use a custom validator which just wraps `rules::length`:
```rust
#[derive(garde::Validate)]
struct Test {
    //                                                  min  max
    //                                                    v  v
    #[garde(custom(|v, _| garde::rules::length::apply(v, (2, 2))))]
    field: String,
}
```

**Comment by jprochazk** [comment]
...or update to [`0.11.2`](https://github.com/jprochazk/garde/releases/tag/v0.11.2) 🙂. Thanks for reporting!
