### ISSUE TITLE
Support NewType pattern

### ISSUE THREAD

**Issue by absolutejam** [jprochazk/garde#50]
Howdy,

Thanks for publishing this crate!

I'm currently toying with it to understand how I can leverage it, but I've hit a bit of a snag when it comes to some of my domain types which follow the NewType pattern. 

For example, this is what I currently have:

```rust
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(transparent)]
struct Username {
  name: String,
}

impl Username {
  pub fn new(name: String) -> Result<Self, Error> {
    // perform validation, returning Err on failure
    Ok(Username { name })
  }

  pub fn value(self) -> String {
    self.name
  }
}
```

*(I've also seen a similar approach with tuple structs and a wrapper `mod` to change the accessibility of the inner tuple value)*

When trying to use `garde`, I want to be able to transparently validate the `name` field of my `Username` struct, but if I add the  derive macros like so:

```rust
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Validate)]
struct Username {
  #[garde(ascii, length(min = 3)]
  name: String,
}
```

And when I want to print out a flattened version of the error message:

```rust
let username_res = Username::new("bo".to_owned());
match username_res {
  Ok(_) => todo!(),
  Err(err) => println!("{:#?}", err.flatten()),
}
```

It shows the following:

```json
 [
    (
        "value.value",
        Error {
            message: "length is lower than 3",
        },
    )
]
```

It would be nice if there was a similar feature to `serde`'s `transparent` field macro so that it basically ignored the outer struct.

```rust
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(transparent)]
#[garde(transparent(name))]
struct Username {
  name: String,
}
```

I'm not sure of the best way to represent this - maybe with its own `Errors` instance, eg. `Errors::Transparent`, or possibly just re-use `Errors::Simple`?

Then the printed representation could look something like:

```json
 [
    (
        "name", // taken from the inside the `transparent` macro
        Error {
            message: "length is lower than 3",
        },
    )
]
```

(given an appropriate `match` clause)

If you think this is an appropriate feature/implementation, I'm happy to try and implement it, but I warn you that my Rust-fu is very fresh!

---

I'm also trying to think of a good way of combining the validation of these wrapper types in a cohesive way instead of my current ad-hoc pattern:

```rust
// uses `multi_try` crate

let username_result = Username::new("bob".to_owned());
let email_result = Email::new("bob@bar.com".to_owned());
let contact_info_result = ContactInfo::new("something".to_owned());

let (username, email, contact_info) = username_result.and_try(email_result).and_try(contact_info_result)?;
// from Result<(Username, Email, ContactInfo), Vec<Errors>>
```

It would be amazing to be able to somehow define a translation like

```rust
#[garde(to_type = CreateUserCommand)]
struct CreateUserRequest {
  username: String,
  email: String,
  #[garde(to_field = "contact_information")] // renamed field
  contact_info: String,
}

// given that each field's type in `CreateUserRequest` implements `Validate`,
// could we map into the following type...

struct CreateUserCommand {
  username: Username,
  email: Email,
  contact_information: ContactInfo,
}
```

but I think that might be a bit out of scope for now :wink:

**Comment by jprochazk** [comment]
The `value.` is inserted as the "base path" during error flattening:

https://github.com/jprochazk/garde/blob/719c7f8bf8dfa6fbd11c9c14eeb793ce1b448e3d/garde/src/error.rs#L133-L163

It doesn't really have to be there, and I'd be fine with removing it, so there's no need to implement an extra attribute for this. It should be possible by duplicating the match in `flatten_inner` to remove the initial `value` in the key:

```rust
pub fn flatten(&self) -> Vec<(String, Error)> {
    fn flatten_inner(out: &mut Vec<(String, Error)>, current_path: String, errors: &Errors) {
        // <snip>
    }

    let mut errors = vec![];
    // instead of calling `flatten_inner`, perform a match here, and only
    // when recursing use `flatten_inner`
    match {
        Errors::Simple(e) => errors.push(("value", e)),
        Errors::Nested(outer, inner) => {
            errors.push(("value", outer));
            flatten_inner(&mut errors, "value", inner);
        }
        Errors::List(e) => for (i, e) in e.iter().enumerate() {
            flatten_inner(&mut errors, "[{i}]", e);
        },
        Errors::Fields(e) => for (key, e) in e.iter() {
            flatten_inner(&mut errors, key, e);
        },
    }
    errors
}
```


Realistically, `Simple` and `Nested` should never occur here because the top-level is always `List` for [tuple structs](https://github.com/jprochazk/garde/blob/719c7f8bf8dfa6fbd11c9c14eeb793ce1b448e3d/garde_derive/src/emit.rs#L155), and `Fields` for [structs with named fields](https://github.com/jprochazk/garde/blob/719c7f8bf8dfa6fbd11c9c14eeb793ce1b448e3d/garde_derive/src/emit.rs#L113).

**Comment by absolutejam** [comment]
Thanks for the reply!

The `flatten()` function was just an example of printing a representation. It's the same issue with `println!("{:#?}", errors)`

*(As an side, it might be nice to be able to configure the output format for `flatten` by providing it a trait impl/function - with a default implementation shipping with the lib. But I guess you could also just reimpliment `flatten` however you need with little effort 🤷 )*

Example output from `println!`
```
Fields(
    {
        "name": Fields(
            {
                "value": Simple(
                    [
                        Error {
                            message: "length is lower than 3",
                        },
                    ],
                ),
            },
        ),
        "summary": Fields(
            {
                "value": Simple(
                    [
                        Error {
                            message: "length is greater than 5",
                        },
                    ],
                ),
            },
        ),
    },
)
```

since the actual representation is `Fields` -> `Simple` -> value.

Whereas I'm suggesting this attribute could omit the `Fields` level. 

This makes it more obvious to the consumer, as they're likely not aware of this level of indirection - ie. a user sending a request containing `{ "name": "foo" }` doesn't know that's going to have the name 'wrapped' by a NewType.

Does that make sense?


---

On a side note, I realised that I can deserialize straight to my 'validated' struct via. my web framework (Actix web) & serde and then call `.validate()` on it to validate it after the fact 🤦 This makes things _so_ much more manageable and seems to be a really useful pattern for the NewType approach. 

I've also implemented a wrapper type that's transparent to serde, and it forces me to call `.validate()` before getting access to the inner value

```rust
#[derive(Debug, Deserialize, Validate)]
struct CreateFooRequest {
  #[garde(dive)]
  username: Username,
  #[garde(dive)]
  email: Email,
  #[garde(dive)]
  contact_information: ContactInfo,
}

#[post("/foo")]
pub async fn create_foo(json_body: Json<NotValidated<CreateFooRequest>>) -> Result<Json<FooId>> {
    let req: CreateFooRequest = body
        .into_inner() // NotValidated<CreateFooRequest> -- NotValidated implements #[serde(transparent)]
        .validate() // Result<Validated<CreateFooRequest>, Errors>
        .map_err(|errs| errors::ErrorUnprocessableEntity(errs.to_string()))? // Validated<CreateFooRequest>
        .value() // => CreateFooRequest
```

**Comment by jprochazk** [comment]
I see what you're asking for now. I think something like `#[garde(dive, flatten)]` as a field-level attribute could work. The actual implementation would be very similar to `#[garde(dive)]`. If you plan to implement this, here's an outline of how you could do that:

Add a new `RawRuleKind`

https://github.com/jprochazk/garde/blob/719c7f8bf8dfa6fbd11c9c14eeb793ce1b448e3d/garde_derive/src/model.rs#L68

This new rule will need a corresponding arm in the parser:

https://github.com/jprochazk/garde/blob/719c7f8bf8dfa6fbd11c9c14eeb793ce1b448e3d/garde_derive/src/syntax.rs#L265-L291

In this case, the raw rule becomes an attribute on a field, so add a new field `flatten` here:

https://github.com/jprochazk/garde/blob/719c7f8bf8dfa6fbd11c9c14eeb793ce1b448e3d/garde_derive/src/model.rs#L124

It's an attribute which is mutually exclusive with `skip`, so it should be added to `is_empty` here:

https://github.com/jprochazk/garde/blob/719c7f8bf8dfa6fbd11c9c14eeb793ce1b448e3d/garde_derive/src/model.rs#L136

The `RawRuleKind` is converted to a `ValidateRule` in `check.rs`, and for "attribute rules" like `dive` and `flatten`, the field is set directly:

https://github.com/jprochazk/garde/blob/719c7f8bf8dfa6fbd11c9c14eeb793ce1b448e3d/garde_derive/src/check.rs#L227-L233

`flatten` would work exactly like `dive` in the above snippet.

`flatten` should always be combined with `dive`, so there needs to be a check for that in `check.rs`, similar to how `skip` is checked here:

https://github.com/jprochazk/garde/blob/719c7f8bf8dfa6fbd11c9c14eeb793ce1b448e3d/garde_derive/src/check.rs#L175-L180

Note: `error.maybe_fold` calls `combine(e)` on the error if it is already `Some`, otherwise if it is `None`, it sets it to `Some(e)`. It's used because the proc macro should always emit as many errors at once as it can.

This `flatten` field will then be used to drive the emit here:

https://github.com/jprochazk/garde/blob/719c7f8bf8dfa6fbd11c9c14eeb793ce1b448e3d/garde_derive/src/emit.rs#L79-L109

And here:

https://github.com/jprochazk/garde/blob/719c7f8bf8dfa6fbd11c9c14eeb793ce1b448e3d/garde_derive/src/emit.rs#L124-L151

If `field.dive && field.flatten`, the emit should be something like:

```rust
__garde_errors.push_all(
    ::garde::validate::Validate(&#binding, __garde_user_ctx)
        .err()
        .unwrap_or_else(::garde::error::Errors::empty())
);
```

It's important to note here that `errors.push` ignores empty errors. The implementation of `push_all` would match on the `Errors` returned from the `validate` call, and call `push` on all of the inner errors, but it would not recurse. Untested example:

```rust
fn unwrap_one_level_into(errors: Errors, out: &mut SimpleErrorBuilder) {
    match errors {
        Errors::Simple(errors) => {
            for e in errors { out.push(e) }
        }
        Errors::Nested(outer) => {
            for e in errors { out.push(e) }
            out.push(e);
        }
        Errors::List(errors) => {
            for e in errors { out.push(e) }
        }
        Errors::Fields(errors) => {
            for (_, e) in errors { out.push(e) }
        }
    }
}
```

**Comment by jprochazk** [comment]
> I've also implemented a wrapper type that's transparent to serde, and it forces me to call .validate() before getting access to the inner value

There is a wrapper type like this already exposed by the library, `Unvalidated`. But it is not `#[repr(transparent)]` nor `#[serde(transparent)]`, which I now realise makes it kind of useless for the exact reason I added `#[derive(Deserialize)]` onto it!

**Comment by jprochazk** [comment]
Since I wrote up the instructions above, some things have changed. It should be possible to make a container-level `transparent` attribute work for unary tuple structs.

A type like
